using System.Collections.Generic;

public static class BuiltinTraits
{
    public static readonly Dictionary<string, CharacterInfo> AllTraits = new Dictionary<string, CharacterInfo>
    {
        ["Active"] = new CharacterInfo {
            Index = 1,
            Category = 0,
            Name = "Active",
            Icon = "gamescene/ui/ui_canvas/icon/skill/Icon_Passive_Horse",
            T_Name = "Active",
            EffectValue_A = 3.0f,
            EffectValue_B = 0.0f,
            Description = "Dexterity <color=#1E8A00>+3</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)1 },
            List_AbilityValue = new List<float> { 3.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Muscular"] = new CharacterInfo {
            Index = 3,
            Category = 0,
            Name = "Muscular",
            Icon = "gamescene/ui/buildingicon/ArenaIcon",
            T_Name = "Muscular",
            EffectValue_A = 3.0f,
            EffectValue_B = 0.0f,
            Description = "Strength <color=#1E8A00>+3</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)0 },
            List_AbilityValue = new List<float> { 3.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Gifted"] = new CharacterInfo {
            Index = 5,
            Category = 0,
            Name = "Gifted",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Encyclopedia",
            T_Name = "Gifted",
            EffectValue_A = 3.0f,
            EffectValue_B = 0.0f,
            Description = "Intelligence <color=#1E8A00>+3</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)2 },
            List_AbilityValue = new List<float> { 3.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Big"] = new CharacterInfo {
            Index = 7,
            Category = 0,
            Name = "Big",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_CCTV",
            T_Name = "Big",
            EffectValue_A = 0.25f,
            EffectValue_B = 0.0f,
            Description = "Size <color=#1E8A00>+25%</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)512 },
            List_AbilityValue = new List<float> { 0.25f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Smol"] = new CharacterInfo {
            Index = 9,
            Category = 0,
            Name = "Smol",
            Icon = "gamescene/character/team/bufficon/Icon_Children",
            T_Name = "Smol",
            EffectValue_A = -0.25f,
            EffectValue_B = 0.0f,
            Description = "Size <color=#C83232>-25%</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)512 },
            List_AbilityValue = new List<float> { -0.25f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Amphibious"] = new CharacterInfo {
            Index = 11,
            Category = 0,
            Name = "Amphibious",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_DrownX",
            T_Name = "Amphibious",
            EffectValue_A = 1.0f,
            EffectValue_B = 0.0f,
            Description = "Able to breathe in water",
            List_Ability = new List<Res_Ability> { (Res_Ability)106 },
            List_AbilityValue = new List<float> { 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Strong Feet"] = new CharacterInfo {
            Index = 13,
            Category = 0,
            Name = "Strong Feet",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_KnockX",
            T_Name = "Strong Feet",
            EffectValue_A = 1.0f,
            EffectValue_B = 0.0f,
            Description = "Able to walk on burning tiles",
            List_Ability = new List<Res_Ability> { (Res_Ability)107 },
            List_AbilityValue = new List<float> { 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Loyal"] = new CharacterInfo {
            Index = 15,
            Category = 0,
            Name = "Loyal",
            Icon = "gamescene/ui/ui_canvas/icon/timetable/Icon_RestTime",
            T_Name = "Loyal",
            EffectValue_A = 1.0f,
            EffectValue_B = 0.0f,
            Description = "Will never rebel",
            List_Ability = new List<Res_Ability> { (Res_Ability)105 },
            List_AbilityValue = new List<float> { 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Good Natured"] = new CharacterInfo {
            Index = 17,
            Category = 0,
            Name = "Good Natured",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_CrimX",
            T_Name = "Good Natured",
            EffectValue_A = 1.0f,
            EffectValue_B = 0.0f,
            Description = " Will never commit crime",
            List_Ability = new List<Res_Ability> { (Res_Ability)110 },
            List_AbilityValue = new List<float> { 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Jack of All Trades"] = new CharacterInfo {
            Index = 4000,
            Category = 0,
            Name = "Jack of All Trades",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_AllStat",
            T_Name = "Jack of All Trades",
            EffectValue_A = 1.0f,
            EffectValue_B = 0.0f,
            Description = "STR, DEX and INT <color=#1E8A00>+1</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)0, (Res_Ability)1, (Res_Ability)2 },
            List_AbilityValue = new List<float> { 1.0f, 1.0f, 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Veteran"] = new CharacterInfo {
            Index = 4001,
            Category = 0,
            Name = "Veteran",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_AssembleBuff",
            T_Name = "Veteran",
            EffectValue_A = 1.0f,
            EffectValue_B = 0.0f,
            Description = "ATK and DEF <color=#1E8A00>+1</color>, HP <color=#C83232>+20</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)5, (Res_Ability)6, (Res_Ability)7 },
            List_AbilityValue = new List<float> { 1.0f, 1.0f, 20.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Natural Angler"] = new CharacterInfo {
            Index = 4002,
            Category = 0,
            Name = "Natural Angler",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Fishing",
            T_Name = "Natural Angler",
            EffectValue_A = 1.0f,
            EffectValue_B = 0.0f,
            Description = "Fish caught <color=#1E8A00>+1</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)243 },
            List_AbilityValue = new List<float> { 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Steady"] = new CharacterInfo {
            Index = 4007,
            Category = 0,
            Name = "Steady",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_KnockX",
            T_Name = "Steady",
            EffectValue_A = 1.0f,
            EffectValue_B = 0f,
            Description = "Prevent knockback in combat",
            List_Ability = new List<Res_Ability> { (Res_Ability)23 },
            List_AbilityValue = new List<float> { 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Table Eater"] = new CharacterInfo {
            Index = 4011,
            Category = 0,
            Name = "Table Eater",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Table",
            T_Name = "Table Eater",
            EffectValue_A = 10.0f,
            EffectValue_B = 8.0f,
            Description = "Happiness <color=#1E8A00>+10</color> after eating at a table",
            List_Ability = new List<Res_Ability>(),
            List_AbilityValue = new List<float>(),
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Pyromaniac"] = new CharacterInfo {
            Index = 4012,
            Category = 0,
            Name = "Pyromaniac",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Firecracker",
            T_Name = "Pyromaniac",
            EffectValue_A = 1.0f,
            EffectValue_B = 0f,
            Description = "Burns enemies on attack",
            List_Ability = new List<Res_Ability> { (Res_Ability)218 },
            List_AbilityValue = new List<float> { 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Hard Worker"] = new CharacterInfo {
            Index = 106,
            Category = 1,
            Name = "Hard Worker",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_AnvilEffect",
            T_Name = "Hard Worker",
            EffectValue_A = 0.2f,
            EffectValue_B = -999f,
            Description = "Production efficiency <color=#1E8A00>+20%</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)13 },
            List_AbilityValue = new List<float> { 0.2f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Hauler"] = new CharacterInfo {
            Index = 108,
            Category = 1,
            Name = "Hauler",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Movement",
            T_Name = "Hauler",
            EffectValue_A = 2.0f,
            EffectValue_B = -999f,
            Description = "Carry capacity <color=#1E8A00>+2</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)3 },
            List_AbilityValue = new List<float> { 2.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Regenerative"] = new CharacterInfo {
            Index = 110,
            Category = 1,
            Name = "Regenerative",
            Icon = "gamescene/character/team/bufficon/Icon_HpGen",
            T_Name = "Regenerative",
            EffectValue_A = 1.0f,
            EffectValue_B = -999f,
            Description = "Health regeneration <color=#1E8A00>+1</color> per tick",
            List_Ability = new List<Res_Ability> { (Res_Ability)202 },
            List_AbilityValue = new List<float> { 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Forceful"] = new CharacterInfo {
            Index = 112,
            Category = 1,
            Name = "Forceful",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Push",
            T_Name = "Forceful",
            EffectValue_A = 1.0f,
            EffectValue_B = 0.0f,
            Description = "Knocks back enemies on attack",
            List_Ability = new List<Res_Ability> { (Res_Ability)217 },
            List_AbilityValue = new List<float> { 1.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Lucky"] = new CharacterInfo {
            Index = 113,
            Category = 1,
            Name = "Lucky",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Dependency",
            T_Name = "Lucky",
            EffectValue_A = 25.0f,
            EffectValue_B = -999f,
            Description = "<color=#1E8A00>+25%</color> chance to get an additional resource when mining",
            List_Ability = new List<Res_Ability> { (Res_Ability)207 },
            List_AbilityValue = new List<float> { 25.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Heavy Handed"] = new CharacterInfo {
            Index = 115,
            Category = 1,
            Name = "Heavy Handed",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_RangeAttack",
            T_Name = "Heavy Handed",
            EffectValue_A = 2.0f,
            EffectValue_B = -999f,
            Description = "<color=#1E8A00>+2</color> to attack power",
            List_Ability = new List<Res_Ability> { (Res_Ability)5 },
            List_AbilityValue = new List<float> { 2.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Thick Skinned"] = new CharacterInfo {
            Index = 116,
            Category = 1,
            Name = "Thick Skinned",
            Icon = "gamescene/character/team/bufficon/Icon_DefenceMode",
            T_Name = "Thick Skinned",
            EffectValue_A = 2.0f,
            EffectValue_B = -999f,
            Description = "<color=#1E8A00>+2</color> to defense",
            List_Ability = new List<Res_Ability> { (Res_Ability)6 },
            List_AbilityValue = new List<float> { 2.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Nimble"] = new CharacterInfo {
            Index = 118,
            Category = 1,
            Name = "Nimble",
            Icon = "gamescene/character/team/bufficon/Icon_Dodge",
            T_Name = "Nimble",
            EffectValue_A = 20.0f,
            EffectValue_B = -999f,
            Description = "<color=#1E8A00>+20%</color> to dodge chance",
            List_Ability = new List<Res_Ability> { (Res_Ability)200 },
            List_AbilityValue = new List<float> { 20.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Builder"] = new CharacterInfo {
            Index = 4003,
            Category = 1,
            Name = "Builder",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_BuildCost2",
            T_Name = "Builder",
            EffectValue_A = 20.0f,
            EffectValue_B = 0f,
            Description = "Construction efficiency <color=#1E8A00>+20%</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)241 },
            List_AbilityValue = new List<float> { 20.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Spelunker"] = new CharacterInfo {
            Index = 4004,
            Category = 1,
            Name = "Spelunker",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Mining",
            T_Name = "Spelunker",
            EffectValue_A = 20.0f,
            EffectValue_B = 0f,
            Description = "Gathering and mining efficiency <color=#1E8A00>+20%</color>",
            List_Ability = new List<Res_Ability> { (Res_Ability)227 },
            List_AbilityValue = new List<float> { 20.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Pollinator"] = new CharacterInfo {
            Index = 4005,
            Category = 1,
            Name = "Pollinator",
            Icon = "gamescene/map/tileobject/FlowerObject",
            T_Name = "Pollinator",
            EffectValue_A = 0.5f,
            EffectValue_B = 0f,
            Description = "Pollinates nearby plants every 20 seconds",
            List_Ability = new List<Res_Ability>(),
            List_AbilityValue = new List<float>(),
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Spiritual"] = new CharacterInfo {
            Index = 4006,
            Category = 1,
            Name = "Spiritual",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Stability",
            T_Name = "Spiritual",
            EffectValue_A = 5f,
            EffectValue_B = 0f,
            Description = "Happiness <color=#1E8A00>+5</color> when part of a religion",
            List_Ability = new List<Res_Ability>(),
            List_AbilityValue = new List<float> { 5.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Socialite"] = new CharacterInfo {
            Index = 4008,
            Category = 1,
            Name = "Socialite",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Happiness",
            T_Name = "Socialite",
            EffectValue_A = 3.0f,
            EffectValue_B = 0f,
            Description = "Happiness <color=#1E8A00>+3</color> to nearby citizens for 4 hours",
            List_Ability = new List<Res_Ability>(),
            List_AbilityValue = new List<float>(),
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Master Chef"] = new CharacterInfo {
            Index = 4009,
            Category = 1,
            Name = "Master Chef",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Cooking",
            T_Name = "Master Chef",
            EffectValue_A = 1.0f,
            EffectValue_B = 0f,
            Description = "Finished products <color=#1E8A00>+1</color> at the grill and bakery",
            List_Ability = new List<Res_Ability>(),
            List_AbilityValue = new List<float>(),
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Efficient Smith"] = new CharacterInfo {
            Index = 4010,
            Category = 1,
            Name = "Efficient Smith",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_NormalUpgrade",
            T_Name = "Efficient Smith",
            EffectValue_A = 1.0f,
            EffectValue_B = 0f,
            Description = "Finished products <color=#1E8A00>+1</color> at the furnace and blacksmith",
            List_Ability = new List<Res_Ability>(),
            List_AbilityValue = new List<float>(),
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Sanguine"] = new CharacterInfo {
            Index = 4013,
            Category = 0,
            Name = "Sanguine",
            Icon = "Agamescene/character/team/bufficon/Icon_NewHope",
            T_Name = "Sanguine",
            EffectValue_A = 10.0f,
            EffectValue_B = 0f,
            Description = "Permanent <color=#1E8A00>+10</color> happiness",
            List_Ability = new List<Res_Ability> { Res_Ability.Happy },
            List_AbilityValue = new List<float> { 10.0f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        },
        ["Quick Learner"] = new CharacterInfo {
            Index = 4014,
            Category = 1,
            Name = "Quick Learner",
            Icon = "gamescene/ui/ui_canvas/icon/Icon_Exp",
            T_Name = "Quick Learner",
            EffectValue_A = 0.5f,
            EffectValue_B = 0f,
            Description = "Experience gain <color=#1E8A00>+50%</color>",
            List_Ability = new List<Res_Ability> { Res_Ability.EXP },
            List_AbilityValue = new List<float> { 0.5f },
            List_Mat = new List<TileType>(),
            List_Mat_Num = new List<int>()
        }
    };
} 